language: java
dk:
  - oraclejdk8
sudo: false
install: true

addons:
  sonarcloud:
    organization: "mistahmilla-github" # the key of the org you chose at step #3
    token:
      secure: 4fde32029da8c3fb806ee61583871d0973c11a08 # encrypted value of your token
script:
  # other script steps might be done before running the actual analysis
  mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
before_deploy:
  - cd ..
  - zip -r -j RegTracker.zip /home/travis/build/Mistahmilla/RegTracker/target/RegTracker-1.0-SNAPSHOT.jar /home/travis/build/Mistahmilla/RegTracker/appspec.yml ome/travis/build/Mistahmilla/RegTracker/src/resources/scripts/install.sh || true
  - mkdir -p "dpl_cd_upload"
  - mv RegTracker.zip dpl_cd_upload/RegTracker.zip || true
deploy:
  - provider: s3
    access_key_id: $AWS_KEY_ID # declared in Travis repo settings
    secret_access_key: $AWS_ACCESS_KEY
    local_dir: dpl_cd_upload
    bucket: cycop
    region: us-east-1
    skip_cleanup: true
    acl: public_read
    detect_encoding: true
    on:
      repo: Mistahmilla/RegTracker
      all_branches: true
  - provider: codedeploy
    access_key_id: $AWS_KEY_ID # declared in Travis repo settings
    secret_access_key: $AWS_ACCESS_KEY
    bucket: cycop
    key: RegTracker.zip
    bundle_type: zip
    application: RegTracker
    deployment_group: RegTracker
    region: us-east-1
    on:
      repo: Mistahmilla/RegTracker
      all_branches: true