language: java
dk:
  - oraclejdk8
sudo: false
install: true

addons:
  sonarcloud:
    organization: "mistahmilla-github" # the key of the org you chose at step #3
    token:
      secure: 4fde32029da8c3fb806ee61583871d0973c11a08 # encrypted value of your token
script:
  # other script steps might be done before running the actual analysis
  mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
deploy:
  - provider: codedeploy
    revision_type: github
    access_key_id: $AWS_KEY_ID
    secret_access_key: $AWS_ACCESS_KEY
    application: RegTracker
    deployment_group: RegTracker
    region: us-east-1
    on:
      branch: develop