version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user
hooks:
BeforeInstall:
    - location: src/main/resources/scripts/before-install.sh
      runas: root
ApplicationStart:
    - location: src/main/resources/scripts/install.sh
      timeout: 3600
      runas: root