version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user
hooks:
  ApplicationStop:
    - location: src/main/resources/scripts/stop_application.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: src/main/resources/scripts/before-install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: src/main/resources/scripts/install.sh
      timeout: 300
      runas: root