version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user
hooks:
  ApplicationStart:
      - location: src/main/resources/scripts/install.sh
        timeout: 3600
        runas: root